- menu_name: "Quick Links"

- name: "Contact"
  url: "/contact/"
  title: "Contact"

- name: "News"
  url: "/news/"
  title: "News"

- name: "Helpdesk"
  url: "https://cms-helpdesk.ncas.ac.uk"
  title: "NCAS-CMS Modelling Helpdesk"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscribe to RSS Feed"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
